version: "3.9"
services:

## Maria DB

#  db:
#    image: mariadb
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: example
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

## Mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example